### ISSUE TITLE
api examples not finding sp_process in libsoundpipe.a

### ISSUE THREAD

**Issue by shakfu** [PaulBatchelor/Sporth#2]
Hi Paul,

I was having some trouble trying to compile the `Sporth/examples/api/` examples because of a recurring error (Undefined symbols for architecture x86_64: _sp_process", referenced from..) while noting that `sp_process` is one of your main functions in a recently default compiled libsoundpipe.a 

I then tried `stretcher.c` from the Soundpipe repo against the same version of `libsoundpipe.a` and I got the same error which means that by default `libsoundpipe.a` compiled with a default config doesn't include the `sp_process` symbols.

I then tried again to compile `stretcher.c` against an older and larger (1.5MB vs the recent 1.2MB) version of libsoundpipe.a and it worked fine: `gcc stretcher.c archive/libsoundpipe.a -lsndfile -o stretcher`

I then retried to compile current `libpsoundpipe.a` but this time by commenting out the following in `config.mk`:

```Makefile
#NO_LIBSNDFILE=1
#CFLAGS += -DNO_LIBSNDFILE
```

Retried to compile stretcher again and this time it found `sp_process` but didn't find `sp_ftbl_loadfile`

As you imagine, its slightly confusing -- but it seems it has to do with some conditional compilation options relating to libsndfile.  

Can you please advise which options to compile against current `libsoundpipe` so that I get past these hiccups. I'm trying to incorporate Sporth (libsporth.a) into a Max/MSP external and this project is currently linking against  libsoundpipe.a and also libsndfile.a (as a dependency of libsoundpipe).

Thanks in advance for any clarification on the above,

S

**Comment by PaulBatchelor** [comment]
Right. This is a similar problem to #1, due to changes to Soundpipe `sp_process` and Sporth not catching up. And by changes to `sp_process`, I mean to say that `sp_process` no longer exists. There are good reasons for this. I don't usually like to break stuff like this, but it's a step forward in the right direction.

The quick fix I did for #1 involved [creating a compatible version of sp_process in Sporth](https://github.com/PaulBatchelor/Sporth/commit/025e78e045ec7ccad077297a6603f9afc35d8e76#diff-056e26c97706bc412a3d4975f21c477b262e492254faa67cbd3cfd1d322850cdR748), called `plumber_sp_process`. I've made this a public function, and the "parse_string" API example has been [fixed to work again](https://github.com/PaulBatchelor/Sporth/commit/ef8d77732a93bcb682bc9eafbb22fe3c282c683b).

> I then tried stretcher.c from the Soundpipe repo against the same version of libsoundpipe.a and I got the same error which means that by default libsoundpipe.a compiled with a default config doesn't include the sp_process symbols.

Ugh. yeah. more broken stuff sorry. You're better off using the self-contained version [here](https://github.com/PaulBatchelor/stretcher).

> I'm trying to incorporate Sporth (libsporth.a) into a Max/MSP external and this project is currently linking against libsoundpipe.a and also libsndfile.a (as a dependency of libsoundpipe).

So, `sp_process` isn't used if you're interested in doing realtime stuff like making a max/msp external. Instead, you'd be making calls to `plumber_compute` and then popping samples off the stack with `sporth_stack_pop_float`. As a very relevant example for study, you may want to take a look at how I am doing it in the [sporth~ object for PD](https://github.com/PaulBatchelor/Sporth/blob/be0846bd1d792e2aa893465da90d44c19f5613ec/util/pd/sporth%7E.c#L40-L69). The project does seem to build still, although the main demo will not run because I disabled the mincer ugen. Other than that, I see no reason why it wouldn't still work.

**Comment by shakfu** [comment]
> Right. This is a similar problem to #1, due to changes to Soundpipe sp_process and Sporth not catching up. And by changes to sp_process, I mean to say that sp_process no longer exists. There are good reasons for this. I don't usually like to break stuff like this, but it's a step forward in the right direction.

No worries. Totally understand that some of the code is in flux. Thanks for creating `plumper_sp_process` and fixing the api example in any case.

> So, sp_process isn't used if you're interested in doing realtime stuff like making a max/msp external. Instead, you'd be making calls to plumber_compute and then popping samples off the stack with sporth_stack_pop_float. As a very relevant example for study, you may want to take a look at how I am doing it in the sporth~ object for PD. The project does seem to build still, although the main demo will not run because I disabled the mincer ugen. Other than that, I see no reason why it wouldn't still work.

Yes. I actually had no intention of using `sp_process` except to test out the api examples. The handful of externals in https://github.com/shakfu/sndpipe based on soundpipe modules happily only use `sp_<module>compute` in their respective audio `perform` functions.

Thanks for the tips on getting sporth to work in the Max external. Will investigate and see if I can get something going..

S

**Comment by PaulBatchelor** [comment]
This issue has been fixed in 025e78e045ec7ccad077297a6603f9afc35d8e76.
