### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by xyproto** [PaulBatchelor/Sporth#26]
Hi,

When compiling Sporth on 64-bit Arch Linux with GCC 7.1.1, I get the following error:

```
ugens/cdb.c: In function ‘sporth_cdbtab’:
ugens/cdb.c:177:19: error: ‘sp_ftbl {aka struct sp_ftbl}’ has no member named ‘del’
                 ft->del = 1;
                   ^~
make: *** [Makefile:57: ugens/cdb.o] Error 1
```

Cheers,
Alexander F Rødseth

**Comment by PaulBatchelor** [comment]
Hey Alex,

It looks like you may need to update soundpipe. Make sure you use the
soundpipe version found in the dev branch.

Let me know if that fixes things,

-P


On Aug 20, 2017 10:39, "Alexander F Rødseth" <notifications@github.com>
wrote:

Hi,

When compiling Sporth on 64-bit Arch Linux with GCC 7.1.1, I get the
following error:

ugens/cdb.c: In function ‘sporth_cdbtab’:
ugens/cdb.c:177:19: error: ‘sp_ftbl {aka struct sp_ftbl}’ has no
member named ‘del’
                 ft->del = 1;
                   ^~
make: *** [Makefile:57: ugens/cdb.o] Error 1

Cheers,
Alexander F Rødseth

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PaulBatchelor/Sporth/issues/26>, or mute the thread

**Comment by xyproto** [comment]
Will try that, thanks.

**Comment by PaulBatchelor** [comment]
Hey @xyproto! are you still getting any errors?

**Comment by xyproto** [comment]
Thanks for the reminder, planning to try it today.

**Comment by xyproto** [comment]
By the way, how about splitting out the soundpipe modules to its own repo (with a _master_ and _dev_ branch) but only use the _master_ branch for `sporth` and `soundpipe`? This way, sporth and soundpipe can be stable and easy to install for users, while `soundpipe-modules` can be "fun and ever changing"?

**Comment by xyproto** [comment]
Works with the soundpipe dev branch. :+1:

**Comment by PaulBatchelor** [comment]
Thank  you for the input! 

Now that Sporth is gotten substantially large, it might make more sense now to have a "dev" branch which corresponds to the "dev" branch of Soundpipe, and for the "master" branch of Sporth to use the "master" branch of Soundpipe. That way, people that just want to use Sporth can just do it without having to worry about which branch to use by default.  Thoughts on this?

The soundpipe library really only is comprised of modules. It is the DSP layer for Sporth. Separate the DSP from the language was a deliberate design choice, as Soundpipe by itself can be used in an number of places by itself (Soundpipe is also designed to be taken apart quite easily too, should Soundpipe be inadequate or too large for a particular need, but that is another story). 

Sporth has always more of a "cowboy" codebase in this sense compared to Soundpipe. Sporth has traditionally used the "dev" branch of Soundpipe because Sporth has always used the bleeding edge of Soundpipe. Mainly this is because I like being able to immediately try out and use new modules in Soundpipe for music compositions.
