### ISSUE TITLE
No sound in livecoding mode

### ISSUE THREAD

**Issue by valentinlageard** [PaulBatchelor/Sporth#43]
Hi, not sure if it's a bug or if I'm missing something but I can't use the livecoding mode.
I use linux mint and I launch qjackctl. I then launch sporth with `sporth -b jack -r 44100 -c 1` and I open vim (the vim script has been copied into .vimrc and seems to work). The problem is that sporth does not appear in the qjackctl Connect menu... and I can't therefore connect it to an output. Before building sporth, I uncommented the `BUILD_JACK=1` line in config.mk and config.def.mk.

What am I missing ?
Thanks in advance.

**Comment by valentinlageard** [comment]
Ok I was dumb, sorry. I didn't understood that you have to add the file to the command line such as `sporth -b jack -r 44100 -c 1 my_livecoding_file.sp`...

**Comment by PaulBatchelor** [comment]
Thanks for your interest!

I'll be the first to admit that setting live coding in Sporth is a largely undocumented process. Are things working now? I don't remember where I left things. More recently, I was also using Spigot as a live coding listener. It might be better? https://github.com/paulbatchelor/spigot

To be honest, it's been a while since I've used or looked at Sporth, but I think I left things in a decent enough state. More recently, I've been focusing on a successor to Sporth with more robust hotswapping/live coding capabilities.
